//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioWeb.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.miservicioSoap")]
    public interface miservicioSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ServicioWeb.ServiceReference1.HelloWorldResponse HelloWorld(ServicioWeb.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioWeb.ServiceReference1.HelloWorldResponse> HelloWorldAsync(ServicioWeb.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento presionHarterialResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/presionHarterial", ReplyAction="*")]
        ServicioWeb.ServiceReference1.presionHarterialResponse presionHarterial(ServicioWeb.ServiceReference1.presionHarterialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/presionHarterial", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioWeb.ServiceReference1.presionHarterialResponse> presionHarterialAsync(ServicioWeb.ServiceReference1.presionHarterialRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ServicioWeb.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ServicioWeb.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServicioWeb.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ServicioWeb.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class presionHarterialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="presionHarterial", Namespace="http://tempuri.org/", Order=0)]
        public ServicioWeb.ServiceReference1.presionHarterialRequestBody Body;
        
        public presionHarterialRequest() {
        }
        
        public presionHarterialRequest(ServicioWeb.ServiceReference1.presionHarterialRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class presionHarterialRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int edad;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int sistolica;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int diastolica;
        
        public presionHarterialRequestBody() {
        }
        
        public presionHarterialRequestBody(int edad, int sistolica, int diastolica) {
            this.edad = edad;
            this.sistolica = sistolica;
            this.diastolica = diastolica;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class presionHarterialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="presionHarterialResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServicioWeb.ServiceReference1.presionHarterialResponseBody Body;
        
        public presionHarterialResponse() {
        }
        
        public presionHarterialResponse(ServicioWeb.ServiceReference1.presionHarterialResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class presionHarterialResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string presionHarterialResult;
        
        public presionHarterialResponseBody() {
        }
        
        public presionHarterialResponseBody(string presionHarterialResult) {
            this.presionHarterialResult = presionHarterialResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface miservicioSoapChannel : ServicioWeb.ServiceReference1.miservicioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class miservicioSoapClient : System.ServiceModel.ClientBase<ServicioWeb.ServiceReference1.miservicioSoap>, ServicioWeb.ServiceReference1.miservicioSoap {
        
        public miservicioSoapClient() {
        }
        
        public miservicioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public miservicioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public miservicioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public miservicioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioWeb.ServiceReference1.HelloWorldResponse ServicioWeb.ServiceReference1.miservicioSoap.HelloWorld(ServicioWeb.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ServicioWeb.ServiceReference1.HelloWorldRequest inValue = new ServicioWeb.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ServicioWeb.ServiceReference1.HelloWorldRequestBody();
            ServicioWeb.ServiceReference1.HelloWorldResponse retVal = ((ServicioWeb.ServiceReference1.miservicioSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioWeb.ServiceReference1.HelloWorldResponse> ServicioWeb.ServiceReference1.miservicioSoap.HelloWorldAsync(ServicioWeb.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioWeb.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            ServicioWeb.ServiceReference1.HelloWorldRequest inValue = new ServicioWeb.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ServicioWeb.ServiceReference1.HelloWorldRequestBody();
            return ((ServicioWeb.ServiceReference1.miservicioSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioWeb.ServiceReference1.presionHarterialResponse ServicioWeb.ServiceReference1.miservicioSoap.presionHarterial(ServicioWeb.ServiceReference1.presionHarterialRequest request) {
            return base.Channel.presionHarterial(request);
        }
        
        public string presionHarterial(int edad, int sistolica, int diastolica) {
            ServicioWeb.ServiceReference1.presionHarterialRequest inValue = new ServicioWeb.ServiceReference1.presionHarterialRequest();
            inValue.Body = new ServicioWeb.ServiceReference1.presionHarterialRequestBody();
            inValue.Body.edad = edad;
            inValue.Body.sistolica = sistolica;
            inValue.Body.diastolica = diastolica;
            ServicioWeb.ServiceReference1.presionHarterialResponse retVal = ((ServicioWeb.ServiceReference1.miservicioSoap)(this)).presionHarterial(inValue);
            return retVal.Body.presionHarterialResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioWeb.ServiceReference1.presionHarterialResponse> ServicioWeb.ServiceReference1.miservicioSoap.presionHarterialAsync(ServicioWeb.ServiceReference1.presionHarterialRequest request) {
            return base.Channel.presionHarterialAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioWeb.ServiceReference1.presionHarterialResponse> presionHarterialAsync(int edad, int sistolica, int diastolica) {
            ServicioWeb.ServiceReference1.presionHarterialRequest inValue = new ServicioWeb.ServiceReference1.presionHarterialRequest();
            inValue.Body = new ServicioWeb.ServiceReference1.presionHarterialRequestBody();
            inValue.Body.edad = edad;
            inValue.Body.sistolica = sistolica;
            inValue.Body.diastolica = diastolica;
            return ((ServicioWeb.ServiceReference1.miservicioSoap)(this)).presionHarterialAsync(inValue);
        }
    }
}
